language: ruby
rvm:
 - 2.5.1

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:setup RAILS_ENV=test


script:
  - bundle exec rspec


services:
  - postgresql

cache: bundler
